// export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const START_LOADING = 'START_LOADING'
export const ERROR = 'ERROR'

export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'

export const FETCH_FLOWERS_SUCCESS = 'FETCH_FLOWERS_SUCCESS'
export const FETCH_FLOWERS_ERROR = 'FETCH_FLOWERS_ERROR'

export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR'

export const RIGHT_ANSWER = 'RIGHT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
export const CURRENT_PROGRESS = 'CURRENT_PROGRESS'
export const CURRENT_PROGRESS_RESET = 'CURRENT_PROGRESS_RESET'
export const FINISH_TRUE = 'FINISH_TRUE'
export const FINISH_FALSE = 'FINISH_FALSE'

export const BTN_AGAIN = 'BTN_AGAIN'

export const BTN_TESTS = 'BTN_TESTS'

export const CURRENT_NEW = 'CURRENT_NEW'
export const CURRENT_RESET = 'CURRENT_RESET'

export const ADD_QUESTION = 'ADD_QUESTION'
export const RESET_CREATION = 'RESET_CREATION'

export const SHOW_NOT = 'SHOW_NOT'
export const HIDE_NOT = 'HIDE_NOT'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGIN_ANSWER = 'LOGIN_ANSWER'
export const AUTO_LOGOUT = 'AUTO_LOGOUT'